name: tractian_test_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.2.2
  sqflite: ^2.4.1
  mockito: ^5.4.4
  provider: ^6.1.2
  flutter_svg: ^2.0.14
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

